---
title: "reading_data_from_the_web"
author: "rl3411"
date: "2023-10-12"
output: github_document
---

```{r}
# Load the necessary libraries
library(tidyverse)
library(rvest)
library(httr)
```

Import NSDUH data

```{r}
nsduh_url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

nsduh_html = 
  read_html(nsduh_url)
```

```{r}
nsduh_html |> 
  html_table()
```

```{r}
marj_use_df = 
  nsduh_html |> 
  html_table() |> 
  first() |> 
  slice(-1) # remove first row because it's not helpful
```

Import star wars data

```{r}
swm_url = "https://www.imdb.com/list/ls070150896/"

swm_html = read_html(swm_url)

swm_df = 
  swm_html |> 
  html_elements(".lister-item-header a") |> 
  html_text()

swm_df = 
  swm_html |> 
  html_elements(".lister-item-header a") |> 
  html_text()

swm_gross_rev_vec =
  swm_html |> 
  html_elements(".text-small:nth-child(7) span:nth-child(5)") |> 
  html_text()
```

## APIs

Get water data from NYC Open data

```{r}
nyc_water_df = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") |> 
  content("parsed")
```

BRFSS Data

```{r}
brfss_df = 
  GET("https://data.cdc.gov/resource/acme-vg9e.csv") |> 
  content()

brfss_df = 
  GET("https://data.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) |> 
  content()
```

```{r}
poke_df = 
  GET("https://pokeapi.co/api/v2/pokemon/ditto") |> 
  content()
```







